### ISSUE TITLE
Barcode scanned result is not working

### ISSUE THREAD

**Issue by Suresh5Mythi** [Dynamsoft/barcode-reader-mobile-samples#18]
When I am scanning PDF 417 format barcodes, I get the results as encoded.
example: 
I expect the result to be "First name: xyz123" , but I get "First name: x*yz*2* ", 
This seems to happen only with react-native version 0.69.3, earlier react-native version was 0.64.2, even now this old version code works fine but not the updated project and the dynamsoft barcode reader version that I am using is 9.2.2

**Comment by Dynamsoft-Henry** [comment]
Hello. To help you solve the issue, we need some more information from you.

Since we didn't provide a React Native edition driver's license sample, we don't know how you are parsing the PDF417 barcode text. Would you like to share your project along with a photo of your PDF417 barcode with us? Or just a simple sample that can reproduce the issue.
